### ISSUE TITLE
Error: The execution timeout has expired. The timeout period expired before the operation completed or the server is not responding.

### ISSUE THREAD

**Issue by baleng** [kr55/ssiscataloger#2] opened 2021-06-16 11:07 UTC
Hello i installed this tool on vs ssdt and on ssms. 
i tried to get 3 folders from a ssis db catalog , one gets the error "Error: The execution timeout has expired. The timeout period expired before the operation completed or the server is not responding."
source istance is Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 (X64)   Jul 20 2019 21:42:29   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 14393: ) 
target is my filesystem.
the only difference between the one failed and the two completed is that the 2 completed have only one and 3 dtsx, the one failed has 1799 dtsx.
![image](https://user-images.githubusercontent.com/41946901/122207727-b87aa000-cea2-11eb-99d0-7a8ff0c46e02.png)
in the report :
![image](https://user-images.githubusercontent.com/41946901/122208571-c0870f80-cea3-11eb-91ee-61a316bb66f8.png)
the error is translated in this issues' subject.
thanks

**Comment by kr55** [comment] 2021-06-16 13:04
Hello,

Thank you for providing the details. I see you have 14 projects and 1799 total packages. 
May I know what Is the maximum number of packages you have in a single project. 
I have to try creating a similar scale project to reproduce the issue.

Regards,
Kunal

**Comment by baleng** [comment] 2021-06-16 13:09
Hello Kunal! 
thanks for your feedback. the max number of  packages in a single project is 379.
this is the complete list
2
3
6
10
31
40
56
144
168
179
200
287
294
379

**Comment by kr55** [comment] 2021-06-16 14:29
Hi,

I tried to create multiple projects with ~380 packages each and then performed the same operation as you did. Unfortunately, I **could not reproduce the issue.**


I have a**ttached debug version of the tool** which provides full stacktrace of the errors. Could you please unzip the file and try the same operation with this. This will provide full error info in the report. 
**I can then dig more into the issue once you provide me the report**.

As a workaround, I suggest you to **try running the tool on the server where you source SQL Server** installed. This does not require SSDT or SSMS to run. You can run it **as a standalone tool** too.

Regards,
Kunal

**Comment by baleng** [comment] 2021-06-16 14:52
THANKS KUNAL,
here you here the exception from the report, i'll try to run the tool standalone on the source server. thansk
Error:   in System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   in System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   in System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   in System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   in System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   in System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   in System.Data.SqlClient.TdsParserStateObject.TryReadByteArray(Byte[] buff, Int32 offset, Int32 len, Int32& totalRead)
   in System.Data.SqlClient.TdsParserStateObject.TryReadPlpBytes(Byte[]& buff, Int32 offst, Int32 len, Int32& totalBytesRead)
   in System.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, String columnName)
   in System.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly)
   in System.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   in System.Data.SqlClient.SqlDataReader.GetSqlBinary(Int32 i)
   in Microsoft.SqlServer.Management.IntegrationServices.ProjectInfo.GetProjectBytes()
   in SSISCataog.CatalogOperation.MigrateCatalogProjectsToFS(String directory, String sourceFolderName, Boolean isMigrateEnvironments, Boolean isDeleteSourceFolder, Dictionary`2 replaceParameterValueList)

**Comment by kr55** [comment] 2021-06-18 07:45
Hi,

I tried to investigate the problem. If the build file is very high, it times out from the server itself, and somehow increasing connection timeout does not help.

However, I now managed to add an enhancement so that other projects from that folder can continue.

Would be good if you try out this feature before I publish it to VS marketplace.


With this new build, all other projects except the failed one should proceed in the export (instead of all 14 failures in your case). 

I will still investigate it further if somehow the timeout can be managed but can't promise it.

Regards,
Kunal

**Comment by baleng** [comment] 2021-06-18 08:34
thank you! it's working now, i got all the projects.
![image](https://user-images.githubusercontent.com/41946901/122532068-6b243d00-d020-11eb-8da0-1888da39599e.png)
by the way , trying to buy a coffe for you i got
![image](https://user-images.githubusercontent.com/41946901/122532309-ac1c5180-d020-11eb-9e35-ad24307c3f36.png)

i try to do this by the vs marketplace, thanks!

**Comment by kr55** [comment] 2021-06-18 08:52
Thank you for the coffee.  
The error you received is  because of your regiounal language in Windows. :( For English, it works fine . I will try to fix that too. 
If you are satisfied with the resolution, please close this bug.

**Closed as completed** 2021-06-18 08:56 UTC
